### PR TITLE
Add package.json for npm/yarn installs

### PR DESCRIPTION
**Pull request by amotl**
Dear Miguel,

first things first: Thanks for conceiving and maintaining this little but valuable jQuery plugin!

We added a `package.json` file for making things like `yarn add https://github.com/mgalante/jquery.redirect` possible. It currently reflects the content of the `bower.json` file you already have in the source tree.

Would you consider merging this minor improvement? It would make it easier to use the module from npm and yarn.

With kind regards,
Andreas.

### CODE REVIEW

**Comment by mgalante** [comment]
Thanks for this!

**Comment by mgalante** [comment]
I already publish this on npm! Thanks again

**Comment by amotl** [comment]
Thanks a bunch!

**Comment by amotl** [comment]
> I already publish this on npm!
You did already? I still can't find it when searching on https://www.npmjs.com/. Would you mind sharing a pointer?

**Comment by mgalante** [comment]
https://npmjs.com/package/jquery.redirect
is it correct?

**Comment by amotl** [comment]
I see, thanks. I didn't hit <enter> after searching for "jquery.redirect". Seems like the name hasn't been propagated to the autocompletion index yet.

Sorry for missing that and thanks again!

Cheers,
Andreas.

**Pull request merged**
